### ISSUE TITLE
Unknown database type point requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

### ISSUE THREAD

**Issue by nkamuo** [brick/geo-doctrine#2]
Please how do I resolve this Issue?

**Comment by BenMorel** [comment]
Hi, you need to register geo doctrine types:

```php
use Doctrine\DBAL\Types\Type;
use Brick\Geo\Doctrine\Types\PointType;

Type::addType('Point', PointType::class);
```

If you're using Symfony:

```yaml
doctrine:
  dbal:
    types:
      Point: Brick\Geo\Doctrine\Types\PointType
    mapping_types:
      Point: Point

```

**Comment by BenMorel** [comment]
Actually I'll leave this issue open until the README is updated with this info.

**Comment by nkamuo** [comment]
Hello. Thanks for your response.
I just figured that out now and it works.
Thanks again.

**Comment by kor3k** [comment]
if you're using Symfony, you can do something like this:

```php
<?php declare(strict_types=1);

namespace App\Geometry;

use Brick\Geo\Doctrine\Functions;
use Brick\Geo\Doctrine\Types;
use Brick\Geo\Engine;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Exception as DBALException;
use Symfony\Component\Finder\Finder;
use function Symfony\Component\String\u;

class GeometryDoctrineSetup
{
    private const TYPES_PATH = '/vendor/brick/geo-doctrine/src/Types';
    private const FUNCTIONS_PATH = '/vendor/brick/geo-doctrine/src/Functions';

    private const TYPES_NAMESPACE = 'Brick\\Geo\\Doctrine\\Types\\';
    private const FUNCTIONS_NAMESPACE = 'Brick\\Geo\\Doctrine\\Functions\\';

    private Engine\GeometryEngine $engine; 

    public function __construct(private readonly EntityManagerInterface $em, private readonly string $projectDir)
    {
    }

    public function initMappingTypes(): void
    {
        $finder = new Finder();
        $finder->in($this->projectDir.self::TYPES_PATH)->files()->name('*.php');

        foreach($finder as $file) {
            $name = u($file->getFilenameWithoutExtension())->trimSuffix('Type')->toString();
            $class = self::TYPES_NAMESPACE.$file->getFilenameWithoutExtension();

            try {
                Type::addType($name, $class);
            } catch (DBALException $e) {
                continue;
            }
            $this->em->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping($name, $name);
        }
    }

    public function initFunctions(): void
    {
        $finder = new Finder();
        $finder->in($this->projectDir.self::FUNCTIONS_PATH)->files()->name('*.php')->notName('Abstract*.php');

        foreach($finder as $file) {
            $name = sprintf('ST_%s', u($file->getFilenameWithoutExtension())->trimSuffix('Function')->toString());
            $class = self::FUNCTIONS_NAMESPACE.$file->getFilenameWithoutExtension();
            $this->em->getConfiguration()->addCustomStringFunction($name, $class);
        }
    }

    public function initEngine(): void
    {
        $this->engine = new Engine\PDOEngine(pdo: $this->em->getConnection()->getNativeConnection(), useProxy: true);
    }

    public function init(): void
    {
        $this->initMappingTypes();
        $this->initFunctions();
        $this->initEngine();
    }

    public function getEngine(): Engine\GeometryEngine
    {
        return $this->engine;
    }
}

```

and

```yaml
services:
  App\Geometry\GeometryDoctrineSetup:
    lazy: false
    arguments:
      $em: '@doctrine.orm.default_entity_manager'
      $projectDir: '%kernel.project_dir%'
    tags:
      - { name: kernel.event_listener , event: kernel.request , method: init , priority: 999 }
      - { name: kernel.event_listener , event: console.command , method: init , priority: 999 }
```

**Comment by DpVic** [comment]
> Hi, you need to register geo doctrine types:
> 
> ```
> use Doctrine\DBAL\Types\Type;
> use Brick\Geo\Doctrine\Types\PointType;
> 
> Type::addType('Point', PointType::class);
> ```
> 
> If you're using Symfony:
> 
> ```yaml
> doctrine:
>   dbal:
>     types:
>       Point: Brick\Geo\Doctrine\Types\PointType
>     mapping_types:
>       Point: Point
> ```
I don't know why, but using capital letters first will trigger the following error

```
Unknown column type "polygon" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::a  
  ddType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during  
   database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform  
  #registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty yo  
  u might have a problem with the cache or forgot some mapping information. 
  ```
  
Setting the types to lowercase solves the problem
  
```yaml
  doctrine:
    dbal:
        default_connection: default
        types:
            polygon: Brick\Geo\Doctrine\Types\PolygonType
        connections:
            default:
                mapping_types:
                    polygon: polygon
```
Then, I register my column as follows:

```php
  #[ORM\Column(type: 'polygon', nullable: false)]
  private null|Polygon $geometry = null;
```
Maybe I missed a capital letter somewhere, but I don't think so. I hope this helps someone.
