### ISSUE TITLE
Help using on symfony controller

### ISSUE THREAD

**Issue by xabikip** [brick/geo-doctrine#3]
I'm trying to use PointType in my symfony project, but I don't know how to use on my controller. Can you help me or give an example please?

Here my `config/packages/doctrine.yaml` config:
```
doctrine:
    dbal:
        types:
            Point: Brick\Geo\Doctrine\Types\PointType
        mapping_types:
            Point: Point
````
Then in my Entity:

```
use Brick\Geo\Doctrine\Types\PointType as Point;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User 
{
   
    #[ORM\Column(type: 'Point', nullable:true)]
    private $latlong;

    public function getLatlong(): ?Point
    {
        return $this->latlong;
    }

    public function setLatlong(Point $latlong): self
    {
        $this->latlong = $latlong;

        return $this;
    }
````
And, how can I use `$user->setLatlong();` inside of my controller?

````
    public function myfunction(Request $request, EntityManagerInterface $entityManager): Response
    {   
        $user = new user();
        $pointType = //how can create PointType 
        $user->setLatlong($pointType);
        $entityManager->persist($user);
        $entityManager->flush();

        return $this->render('mytemplate.html.twig');
    }

Thanks
